# Generated by Django 5.2.7 on 2025-10-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Кол-во')),
                ('state', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Отправлена'), ('APPROVED', 'Согласована'), ('ORDERED', 'Заказано'), ('CLOSED', 'Закрыта'), ('REJECTED', 'Отклонена')], db_index=True, default='DRAFT', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='procurement/', verbose_name='Приложение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-created_at'],
            },
        ),
    ]
