# Generated by Django 5.2.7 on 2025-10-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('procurement', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='Склад'),
        ),
    ]
