# Generated by Django 5.2.7 on 2025-10-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер'),
        ),
    ]
