# Generated by Django 5.2.7 on 2025-10-27 10:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В работе'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_book', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='По учёту')),
                ('qty_fact', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='Факт')),
                ('delta', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='Разница')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Строка инвентаризации',
                'verbose_name_plural': 'Строки инвентаризации',
            },
        ),
    ]
