# Generated by Django 5.2.7 on 2025-10-23 12:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_supplier'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В работе'), ('CLOSED', 'Закрыт')], default='DRAFT', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_book', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='По учёту')),
                ('qty_fact', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='Факт')),
                ('delta', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='Разница')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory_count.inventorycount', verbose_name='Инвентаризация')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Строка инвентаризации',
                'verbose_name_plural': 'Строки инвентаризации',
                'indexes': [models.Index(fields=['count', 'location', 'item'], name='inventory_c_count_i_d94b2e_idx')],
                'unique_together': {('count', 'location', 'item')},
            },
        ),
    ]
