# Generated by Django 5.2.7 on 2025-10-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory_count', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory_count.inventorycount', verbose_name='Инвентаризация'),
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='inventorycountline',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.location', verbose_name='Локация'),
        ),
        migrations.AddIndex(
            model_name='inventorycountline',
            index=models.Index(fields=['count', 'location', 'item'], name='inventory_c_count_i_d94b2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycountline',
            unique_together={('count', 'location', 'item')},
        ),
    ]
