# Generated by Django 5.2.7 on 2025-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_type', models.CharField(max_length=64, verbose_name='Тип расчёта/отчёта')),
                ('params', models.JSONField(default=dict, verbose_name='Параметры')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('status', models.CharField(choices=[('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], db_index=True, default='RUNNING', max_length=8, verbose_name='Статус')),
                ('rows_read', models.BigIntegerField(default=0, verbose_name='Строк прочитано')),
                ('rows_written', models.BigIntegerField(default=0, verbose_name='Строк записано')),
                ('result_ref', models.CharField(blank=True, max_length=255, verbose_name='Результат (ссылка/путь)')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Журнал расчёта',
                'verbose_name_plural': 'Журналы расчётов',
                'ordering': ['-started_at'],
            },
        ),
    ]
