# Generated by Django 5.2.7 on 2025-10-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_supplier'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(blank=True, max_length=32, verbose_name='Рейс/маршрут')),
                ('arrived_at', models.DateTimeField(verbose_name='Прибытие')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-arrived_at'],
            },
        ),
        migrations.CreateModel(
            name='ArrivalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Кол-во')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transport.arrival', verbose_name='Поставка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.location', verbose_name='Локация назначения')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ')),
            ],
            options={
                'verbose_name': 'Строка поставки',
                'verbose_name_plural': 'Строки поставок',
            },
        ),
        migrations.CreateModel(
            name='TransportUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TRUCK', 'Авто'), ('TRAIN', 'ЖД'), ('SHIP', 'Судно'), ('OTHER', 'Другое')], default='TRUCK', max_length=8, verbose_name='Тип')),
                ('number', models.CharField(db_index=True, max_length=32, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
                'ordering': ['type', 'number'],
                'unique_together': {('type', 'number')},
            },
        ),
        migrations.AddField(
            model_name='arrival',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.transportunit', verbose_name='Транспорт'),
        ),
    ]
