# Generated by Django 5.2.7 on 2025-10-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kind',
            field=models.CharField(choices=[('ORE', 'Руды'), ('TOOL', 'Инструменты'), ('EQUIPMENT', 'Оборудование'), ('CONSUMABLE', 'Расходники')], db_index=True, default='TOOL', max_length=16, verbose_name='Тип'),
        ),
    ]
