# Generated by Django 5.2.7 on 2025-10-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ORE", "Руда"),
                    ("TOOL", "Инструмент"),
                    ("EQUIPMENT", "Оборудование"),
                    ("CONSUMABLE", "Расходник"),
                ],
                db_index=True,
                default="TOOL",
                max_length=16,
                verbose_name="Тип",
            ),
        ),
    ]
