# Generated by Django 5.2.7 on 2025-10-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=64, verbose_name='Сущность')),
                ('operation', models.CharField(max_length=32, verbose_name='Операция')),
                ('payload', models.JSONField(verbose_name='Данные')),
                ('correlation_id', models.CharField(max_length=64, unique=True, verbose_name='Корреляция')),
                ('state', models.CharField(choices=[('PENDING', 'В очереди'), ('SENT', 'Отправлено'), ('ACK', 'Подтверждено'), ('ERROR', 'Ошибка')], db_index=True, default='PENDING', max_length=8, verbose_name='Статус')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('last_error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Очередь синхронизации',
                'verbose_name_plural': 'Очередь синхронизации',
                'indexes': [models.Index(fields=['state', 'created_at'], name='sync_syncqu_state_93197f_idx')],
            },
        ),
    ]
