# Generated by Django 5.2.7 on 2025-10-23 11:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEIPT', 'Приёмка'), ('ISSUE', 'Списание'), ('TRANSFER', 'Перемещение')], max_length=16, verbose_name='Тип операции')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Количество')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Движение',
                'verbose_name_plural': 'Движения',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='Количество')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.location', verbose_name='Локация')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
                'ordering': ['location__warehouse__name', 'location__code'],
            },
        ),
    ]
