# Generated by Django 5.2.7 on 2025-10-23 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='movement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouses.location', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='movement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='movement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouses.location', verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='movement',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('location', 'item')},
        ),
    ]
