# Generated by Django 5.2.7 on 2025-10-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_initial'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('qty_on_hand__gte', 0)), name='non_negative_qty'),
        ),
    ]
