# Generated by Django 5.2.7 on 2025-10-28 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_item_kind"),
        ("inventory", "0003_movement_serial_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="item",
            field=models.ForeignKey(
                limit_choices_to={"kind__in": ["TOOL", "EQUIPMENT", "CONSUMABLE"]},
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.item",
                verbose_name="Номенклатура",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="item",
            field=models.ForeignKey(
                limit_choices_to={"kind__in": ["TOOL", "EQUIPMENT", "CONSUMABLE"]},
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.item",
                verbose_name="Номенклатура",
            ),
        ),
    ]
