# Generated by Django 5.2.7 on 2025-10-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_supplier'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockpile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('capacity_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Вместимость')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Сток-пайл',
                'verbose_name_plural': 'Сток-пайлы',
                'ordering': ['warehouse__name', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockpileAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Текущее кол-во')),
                ('severity', models.CharField(choices=[('WARN', 'Внимание'), ('CRIT', 'Критично')], default='WARN', max_length=8, verbose_name='Важность')),
                ('state', models.CharField(choices=[('OPEN', 'Открыт'), ('ACK', 'Принят'), ('CLOSED', 'Закрыт')], default='OPEN', max_length=8, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stockpile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockpiles.stockpile', verbose_name='Сток-пайл')),
            ],
            options={
                'verbose_name': 'Алерт сток-пайла',
                'verbose_name_plural': 'Алерты сток-пайлов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockpileThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Мин. кол-во')),
                ('max_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Макс. кол-во')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('stockpile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='threshold', to='stockpiles.stockpile', verbose_name='Сток-пайл')),
            ],
            options={
                'verbose_name': 'Порог сток-пайла',
                'verbose_name_plural': 'Пороги сток-пайлов',
            },
        ),
    ]
