# Generated by Django 5.2.7 on 2025-10-30 16:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stockpiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpilealert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда принято'),
        ),
        migrations.AddField(
            model_name='stockpilealert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем принято'),
        ),
        migrations.AddField(
            model_name='stockpilealert',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.CreateModel(
            name='StockpileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEIPT', 'Приёмка'), ('ISSUE', 'Списание'), ('TRANSFER', 'Перемещение')], max_length=16, verbose_name='Тип операции')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Количество')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('from_stockpile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='stockpiles.stockpile', verbose_name='Из сток-пайла')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('stockpile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockpiles.stockpile', verbose_name='Сток-пайл')),
                ('to_stockpile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='stockpiles.stockpile', verbose_name='В сток-пайл')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ')),
            ],
            options={
                'verbose_name': 'Движение сток-пайла',
                'verbose_name_plural': 'Движения сток-пайлов',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='StockpileBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=18, verbose_name='Количество')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('stockpile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stockpiles.stockpile', verbose_name='Сток-пайл')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Остаток сток-пайла',
                'verbose_name_plural': 'Остатки сток-пайлов',
                'ordering': ['stockpile__warehouse__name', 'stockpile__code'],
                'unique_together': {('stockpile', 'item')},
            },
        ),
    ]
