# Generated by Django 5.2.7 on 2025-10-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_supplier'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Мин. кол-во')),
                ('max_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='Макс. кол-во')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Номенклатура')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.location', verbose_name='Локация')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Порог',
                'verbose_name_plural': 'Пороги',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Текущее кол-во')),
                ('severity', models.CharField(choices=[('INFO', 'Инфо'), ('WARN', 'Внимание'), ('CRIT', 'Критично')], default='WARN', max_length=8, verbose_name='Важность')),
                ('state', models.CharField(choices=[('OPEN', 'Открыт'), ('ACK', 'Принят'), ('CLOSED', 'Закрыт')], db_index=True, default='OPEN', max_length=8, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Корреляция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Номенклатура')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.location', verbose_name='Локация')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.uom', verbose_name='ЕИ')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='Склад')),
                ('threshold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thresholds.threshold', verbose_name='Порог')),
            ],
            options={
                'verbose_name': 'Алерт',
                'verbose_name_plural': 'Алерты',
            },
        ),
        migrations.AddIndex(
            model_name='threshold',
            index=models.Index(fields=['warehouse', 'location', 'item'], name='thresholds__warehou_23fdc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threshold',
            unique_together={('warehouse', 'location', 'item')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['state', 'created_at'], name='thresholds__state_d45f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['warehouse', 'location', 'item'], name='thresholds__warehou_28ba0f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['correlation_id'], name='thresholds__correla_4f27e6_idx'),
        ),
    ]
