# Generated by Django 5.2.7 on 2025-10-27 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ore', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orereceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
        migrations.AddField(
            model_name='orereceipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.item', verbose_name='Тип руды'),
        ),
        migrations.AddField(
            model_name='orereceipt',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.location', verbose_name='Локация приёмки'),
        ),
    ]
